services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.ollama
    networks:
      - private-gpt-network
    restart: unless-stopped

  private-gpt:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: private-gpt
    depends_on:
      - ollama
    ports:
      - "8001:8001"
    volumes:
      - ./local_data:/home/worker/app/local_data
      - ./private_gpt:/home/worker/app/private_gpt
      - ./settings.yaml:/home/worker/app/settings.yaml
       - hf-cache:/home/worker/.cache/huggingface 
    environment:
      PORT: 8001
      PGPT_PROFILES: default
      PGPT_MODE: ollama
      PGPT_EMBED_MODE: ollama
    networks:
      - private-gpt-network
    restart: unless-stopped
volumes:
  hf-cache: 
networks:
  private-gpt-network:
    driver: bridge